resolution: 256
dirs:
  - svbrdfs: inria_svbrdfs
    svbrdf_mode: "part/name_part"
    renders: inria_renders
    texture_gamma: 1.0
    count: 199068
  - svbrdfs: cc0_svbrdfs
    svbrdf_mode: "part/name_part"
    renders: cc0_renders
    texture_gamma: 1.0
    count: 30032
  - svbrdfs: mixed_svbrdfs
    svbrdf_mode: "part/name_part"
    renders: mixed_renders
    texture_gamma: 1.0
    count: 98211
loader: !Rendered
  # NOTE: train maps are all rendered at 53 degree FOV (distance = 2.0)
  # we crop them by 75% which gives a 41.1 degree FOV (distance = 2.66)
  crop: 0.75
  flash_weight: 1.0
  other_weight: !uniform_log_sampled [0.02, 1.5]
